/**
 * Replaces the oxlint configuration this project started with. The two rules it
 * actually enforced are carried over unchanged - they were the React rules from the
 * standard Vite react-ts template in the first place, under oxlint's names for them:
 *
 *   react/rules-of-hooks       -> react-hooks/rules-of-hooks
 *   react/only-export-components -> react-refresh/only-export-components
 *
 * so the same code passes and fails for the same reasons. What is new is everything
 * typescript-eslint's recommended set adds on top.
 */

import js from '@eslint/js'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  // Not linted, and not a judgement about any of it: dist is output, node_modules is
  // other people's, and src/api/schema is generated by `npm run codegen` - a finding
  // there is addressed by editing a generator, or more often by not caring.
  {
    ignores: ['dist/**', 'node_modules/**', 'src/api/schema/**'],
  },

  // The application: browser globals, type-aware-adjacent but not type-checked. The
  // typed rules need a program per lint run, which on this project costs more than the
  // findings are worth given `tsc -b` already runs in the same CI job.
  {
    files: ['**/*.{ts,tsx}'],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2023,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
    },
  },

  // Vendored shadcn/ui source. It ships its cva variants alongside the component they
  // style, which is the one thing only-export-components objects to. This override is
  // the one the oxlint config carried, for the same reason.
  {
    files: ['src/components/ui/**'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },

  // Node, not a browser: the codegen script, the e2e drivers and the config files.
  {
    files: ['scripts/**/*.mjs', 'e2e/**/*.mjs', '*.config.{ts,js}'],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: globals.node,
    },
  },

  // Tests run in vitest's globals-free mode, so `expect` and friends are imported
  // rather than ambient. What they do need is the DOM plus node: jsdom in one project
  // and a real node environment in the other.
  {
    files: ['src/**/*.test.{ts,tsx}', 'src/test/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      // Tests assert on shapes the app treats as opaque, and a cast is the honest way
      // to say "this fixture stands in for a generated type".
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
)
