// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationOutbox struct {
	OutboxID    uuid.UUID
	EventID     uuid.UUID
	RoutingKey  string
	Payload     []byte
	CreatedAt   time.Time
	PublishedAt pgtype.Timestamptz
	Attempts    int32
	LastError   pgtype.Text
}

type PurchaseRequest struct {
	RequestID      uuid.UUID
	ItemName       string
	Description    string
	Category       string
	Status         string
	TotalCustomers int32
	TotalQuantity  int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CreatedBy      pgtype.UUID
	TotalOffers    int32
}

type RequestParticipant struct {
	ParticipantID uuid.UUID
	RequestID     uuid.UUID
	CustomerID    uuid.UUID
	Quantity      int32
	JoinedAt      time.Time
}
