// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type PurchaseRequest struct {
	RequestID      uuid.UUID
	ItemName       string
	Description    string
	Category       string
	Status         string
	TotalCustomers int32
	TotalQuantity  int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type RequestParticipant struct {
	ParticipantID uuid.UUID
	RequestID     uuid.UUID
	CustomerID    uuid.UUID
	Quantity      int32
	JoinedAt      time.Time
}
