// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddParticipant(ctx context.Context, arg AddParticipantParams) (RequestParticipant, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (PurchaseRequest, error)
	DeleteParticipant(ctx context.Context, arg DeleteParticipantParams) (int64, error)
	// R1 with a twist: a second customer asking for the same item is not new demand, it is
	// more of the demand that already exists - so there is nothing to create, and this is
	// what says so. Names are compared on request_item_key, so "Espresso Machine",
	// "espresso machine " and "Espresso-Machine" are one request; the oldest open one wins.
	// Only OPEN requests match - a closed one cannot be joined, so naming it opens a fresh
	// request.
	//
	// No FOR UPDATE: creating never writes to the request it finds. Joining is a separate
	// call the customer makes for themselves, and that path takes the lock it needs.
	FindOpenRequestByItemName(ctx context.Context, itemName string) (PurchaseRequest, error)
	// The names an exact match cannot see, by either of the two signals that catch them.
	//
	// score is trigram distance on the normalized key, which is what finds a typo. contains
	// is whole-word containment, which is what finds the same product with more said about
	// it - and it is a separate signal rather than a lower threshold because scoring cannot
	// express it: "Espresso Machine" reaches only .515 against "Espresso Machine Pro Deluxe
	// 2024", below the .538 that "Laptop" reaches against the genuinely different "Laptop
	// Stand". No single number separates those two; containment does.
	//
	// Containment demands two words on the shorter side, which is the whole difference
	// between the case worth catching and the case worth leaving alone. Both are one name
	// inside another: "espresso machine" in "espresso machine pro deluxe 2024", "laptop" in
	// "laptop stand". The first is a product described at more length; the second is a
	// different product that happens to be named after the first. A single word is a
	// category far more often than it is an item, so one word never triggers this.
	//
	// The % operator and @> do the narrowing, because those are the forms the GIN indexes
	// serve; min_score then applies the caller's own floor on top of the 0.3 the schema
	// pins % to. A min_score below 0.3 filters nothing extra - the operator has already
	// dropped those rows - and rows found only by containment are returned whatever they
	// score, which is the point of having a second signal at all.
	FindSimilarOpenRequests(ctx context.Context, arg FindSimilarOpenRequestsParams) ([]FindSimilarOpenRequestsRow, error)
	GetParticipant(ctx context.Context, arg GetParticipantParams) (RequestParticipant, error)
	GetRequest(ctx context.Context, requestID uuid.UUID) (PurchaseRequest, error)
	ListParticipantCustomerIDs(ctx context.Context, requestID uuid.UUID) ([]uuid.UUID, error)
	ListRequests(ctx context.Context, arg ListRequestsParams) ([]PurchaseRequest, error)
	ListRequestsByCustomer(ctx context.Context, customerID uuid.UUID) ([]PurchaseRequest, error)
	// Held for the length of the transaction, keyed on the normalized name. Two customers
	// naming the same brand-new item at the same instant would otherwise both find nothing
	// above and both create a request; with this the second one waits, then finds the first
	// one's. It locks a name, not a row, so there is nothing to lock before the row exists.
	LockItemName(ctx context.Context, itemName string) error
	// Serializes concurrent joins/leaves on the same request so demand recalculation
	// cannot interleave and land on a stale total.
	LockRequest(ctx context.Context, requestID uuid.UUID) (PurchaseRequest, error)
	// R4: the service, not the caller, owns totalCustomers and totalQuantity. Recomputed
	// from request_participant in the same transaction as the mutation that changed it.
	//
	// The status is recomputed with them, because it is the same fact: a request nobody is
	// on is INACTIVE, and the join that puts someone back on it makes it OPEN again. That
	// makes the status derived rather than commanded - there is no call that sets it, so
	// it can never disagree with the participants it describes.
	RecalculateDemand(ctx context.Context, requestID uuid.UUID) (PurchaseRequest, error)
	UpdateParticipantQuantity(ctx context.Context, arg UpdateParticipantQuantityParams) (RequestParticipant, error)
}

var _ Querier = (*Queries)(nil)
