// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddParticipant(ctx context.Context, arg AddParticipantParams) (RequestParticipant, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (PurchaseRequest, error)
	DeleteParticipant(ctx context.Context, arg DeleteParticipantParams) (int64, error)
	GetParticipant(ctx context.Context, arg GetParticipantParams) (RequestParticipant, error)
	GetRequest(ctx context.Context, requestID uuid.UUID) (PurchaseRequest, error)
	ListParticipantCustomerIDs(ctx context.Context, requestID uuid.UUID) ([]uuid.UUID, error)
	ListRequests(ctx context.Context, arg ListRequestsParams) ([]PurchaseRequest, error)
	ListRequestsByCustomer(ctx context.Context, customerID uuid.UUID) ([]PurchaseRequest, error)
	// Serializes concurrent joins/leaves on the same request so demand recalculation
	// cannot interleave and land on a stale total.
	LockRequest(ctx context.Context, requestID uuid.UUID) (PurchaseRequest, error)
	// R4: the service, not the caller, owns totalCustomers and totalQuantity. Recomputed
	// from request_participant in the same transaction as the mutation that changed it.
	RecalculateDemand(ctx context.Context, requestID uuid.UUID) (PurchaseRequest, error)
	UpdateParticipantQuantity(ctx context.Context, arg UpdateParticipantQuantityParams) (RequestParticipant, error)
}

var _ Querier = (*Queries)(nil)
