// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddParticipant(ctx context.Context, arg AddParticipantParams) (RequestParticipant, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (PurchaseRequest, error)
	DeleteParticipant(ctx context.Context, arg DeleteParticipantParams) (int64, error)
	// R1 with a twist: a second customer asking for the same item is not new demand, it is
	// more of the demand that already exists - so there is nothing to create, and this is
	// what says so. Names are compared on request_item_key, so "Espresso Machine",
	// "espresso machine " and "Espresso-Machine" are one request.
	//
	// Every status matches, not just OPEN. INACTIVE is what a request with nobody on it is
	// called - the one a seller opened by offering against an item, and the one whose last
	// participant left - and a join revives either. A second request would have nothing to
	// add to one and would split the demand of the other, so both are found here.
	//
	// OPEN wins when both exist, which only old data can produce: live demand is the better
	// thing to hand a customer, and the oldest breaks any remaining tie.
	//
	// No FOR UPDATE: creating never writes to the request it finds. Joining is a separate
	// call the customer makes for themselves, and that path takes the lock it needs.
	FindRequestByItemName(ctx context.Context, itemName string) (PurchaseRequest, error)
	// The names an exact match cannot see, by either of the two signals that catch them.
	//
	// Every status is searched, for the same reason the exact match searches every status: a
	// request with no buyers on it is the one most worth suggesting, since joining it is
	// what makes it demand again. The status travels with each row, so a caller can say
	// which it is offering.
	//
	// score is trigram distance on the normalized key, which is what finds a typo. contains
	// is whole-word containment, which is what finds the same product with more said about
	// it - and it is a separate signal rather than a lower threshold because scoring cannot
	// express it: "Espresso Machine" reaches only .515 against "Espresso Machine Pro Deluxe
	// 2024", below the .538 that "Laptop" reaches against the genuinely different "Laptop
	// Stand". No single number separates those two; containment does.
	//
	// Containment demands two words on the shorter side, which is the whole difference
	// between the case worth catching and the case worth leaving alone. Both are one name
	// inside another: "espresso machine" in "espresso machine pro deluxe 2024", "laptop" in
	// "laptop stand". The first is a product described at more length; the second is a
	// different product that happens to be named after the first. A single word is a
	// category far more often than it is an item, so one word never triggers this.
	//
	// The % operator and @> do the narrowing, because those are the forms the GIN indexes
	// serve; min_score then applies the caller's own floor on top of the 0.3 the schema
	// pins % to. A min_score below 0.3 filters nothing extra - the operator has already
	// dropped those rows - and rows found only by containment are returned whatever they
	// score, which is the point of having a second signal at all.
	// Status only breaks a tie: a suggestion with buyers already on it is the better one
	// to offer, but never at the cost of a closer name.
	FindSimilarRequests(ctx context.Context, arg FindSimilarRequestsParams) ([]FindSimilarRequestsRow, error)
	GetParticipant(ctx context.Context, arg GetParticipantParams) (RequestParticipant, error)
	GetRequest(ctx context.Context, requestID uuid.UUID) (PurchaseRequest, error)
	ListParticipantCustomerIDs(ctx context.Context, requestID uuid.UUID) ([]uuid.UUID, error)
	ListRequests(ctx context.Context, arg ListRequestsParams) ([]PurchaseRequest, error)
	ListRequestsByCustomer(ctx context.Context, customerID uuid.UUID) ([]PurchaseRequest, error)
	// Held for the length of the transaction, keyed on the normalized name. Two customers
	// naming the same brand-new item at the same instant would otherwise both find nothing
	// above and both create a request; with this the second one waits, then finds the first
	// one's. It locks a name, not a row, so there is nothing to lock before the row exists.
	LockItemName(ctx context.Context, itemName string) error
	// Serializes concurrent joins/leaves on the same request so demand recalculation
	// cannot interleave and land on a stale total.
	LockRequest(ctx context.Context, requestID uuid.UUID) (PurchaseRequest, error)
	// R4: the service, not the caller, owns totalCustomers and totalQuantity. Recomputed
	// from request_participant in the same transaction as the mutation that changed it.
	//
	// The status is recomputed with them, because it is the same fact: a request nobody is
	// on and nobody is selling into is INACTIVE, and either a join or an offer makes it OPEN
	// again. That makes the status derived rather than commanded - there is no call that
	// sets it, so it can never disagree with the counts it describes.
	//
	// This is the only statement that decides a status, which is why SetOfferCount writes
	// its column and then leaves the deciding to this: two places computing it would be two
	// places to disagree. total_offers is read rather than recomputed, because the offers it
	// counts live in another service's database.
	RecalculateDemand(ctx context.Context, requestID uuid.UUID) (PurchaseRequest, error)
	// How many live offers stand on this request, as offer-service counts them. An absolute
	// number rather than a delta, so a call that is retried or arrives twice lands on the
	// same answer instead of drifting away from the truth.
	//
	// It writes the column and nothing else. The status that depends on it is left to
	// RecalculateDemand, which the service calls next in the same transaction.
	SetOfferCount(ctx context.Context, arg SetOfferCountParams) error
	UpdateParticipantQuantity(ctx context.Context, arg UpdateParticipantQuantityParams) (RequestParticipant, error)
}

var _ Querier = (*Queries)(nil)
