// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipant = `-- name: AddParticipant :one
INSERT INTO request_participant (request_id, customer_id, quantity)
VALUES ($1, $2, $3)
RETURNING participant_id, request_id, customer_id, quantity, joined_at
`

type AddParticipantParams struct {
	RequestID  uuid.UUID
	CustomerID uuid.UUID
	Quantity   int32
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) (RequestParticipant, error) {
	row := q.db.QueryRow(ctx, addParticipant, arg.RequestID, arg.CustomerID, arg.Quantity)
	var i RequestParticipant
	err := row.Scan(
		&i.ParticipantID,
		&i.RequestID,
		&i.CustomerID,
		&i.Quantity,
		&i.JoinedAt,
	)
	return i, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO purchase_request (item_name, description, category)
VALUES ($1, $2, $3)
RETURNING request_id, item_name, description, category, status, total_customers, total_quantity, created_at, updated_at
`

type CreateRequestParams struct {
	ItemName    string
	Description string
	Category    string
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (PurchaseRequest, error) {
	row := q.db.QueryRow(ctx, createRequest, arg.ItemName, arg.Description, arg.Category)
	var i PurchaseRequest
	err := row.Scan(
		&i.RequestID,
		&i.ItemName,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.TotalCustomers,
		&i.TotalQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteParticipant = `-- name: DeleteParticipant :execrows
DELETE FROM request_participant
WHERE request_id = $1 AND customer_id = $2
`

type DeleteParticipantParams struct {
	RequestID  uuid.UUID
	CustomerID uuid.UUID
}

func (q *Queries) DeleteParticipant(ctx context.Context, arg DeleteParticipantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteParticipant, arg.RequestID, arg.CustomerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getParticipant = `-- name: GetParticipant :one
SELECT participant_id, request_id, customer_id, quantity, joined_at FROM request_participant
WHERE request_id = $1 AND customer_id = $2
`

type GetParticipantParams struct {
	RequestID  uuid.UUID
	CustomerID uuid.UUID
}

func (q *Queries) GetParticipant(ctx context.Context, arg GetParticipantParams) (RequestParticipant, error) {
	row := q.db.QueryRow(ctx, getParticipant, arg.RequestID, arg.CustomerID)
	var i RequestParticipant
	err := row.Scan(
		&i.ParticipantID,
		&i.RequestID,
		&i.CustomerID,
		&i.Quantity,
		&i.JoinedAt,
	)
	return i, err
}

const getRequest = `-- name: GetRequest :one
SELECT request_id, item_name, description, category, status, total_customers, total_quantity, created_at, updated_at FROM purchase_request
WHERE request_id = $1
`

func (q *Queries) GetRequest(ctx context.Context, requestID uuid.UUID) (PurchaseRequest, error) {
	row := q.db.QueryRow(ctx, getRequest, requestID)
	var i PurchaseRequest
	err := row.Scan(
		&i.RequestID,
		&i.ItemName,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.TotalCustomers,
		&i.TotalQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listParticipantCustomerIDs = `-- name: ListParticipantCustomerIDs :many
SELECT customer_id FROM request_participant
WHERE request_id = $1
ORDER BY joined_at
`

func (q *Queries) ListParticipantCustomerIDs(ctx context.Context, requestID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listParticipantCustomerIDs, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var customer_id uuid.UUID
		if err := rows.Scan(&customer_id); err != nil {
			return nil, err
		}
		items = append(items, customer_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequests = `-- name: ListRequests :many
SELECT request_id, item_name, description, category, status, total_customers, total_quantity, created_at, updated_at FROM purchase_request
WHERE ($1::text IS NULL
       OR item_name ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL
       OR category = $2::text)
  AND ($3::text IS NULL
       OR status = $3::text)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListRequestsParams struct {
	ItemName     pgtype.Text
	Category     pgtype.Text
	Status       pgtype.Text
	ResultOffset int32
	ResultLimit  int32
}

func (q *Queries) ListRequests(ctx context.Context, arg ListRequestsParams) ([]PurchaseRequest, error) {
	rows, err := q.db.Query(ctx, listRequests,
		arg.ItemName,
		arg.Category,
		arg.Status,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurchaseRequest{}
	for rows.Next() {
		var i PurchaseRequest
		if err := rows.Scan(
			&i.RequestID,
			&i.ItemName,
			&i.Description,
			&i.Category,
			&i.Status,
			&i.TotalCustomers,
			&i.TotalQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByCustomer = `-- name: ListRequestsByCustomer :many
SELECT pr.request_id, pr.item_name, pr.description, pr.category, pr.status, pr.total_customers, pr.total_quantity, pr.created_at, pr.updated_at FROM purchase_request pr
JOIN request_participant rp ON rp.request_id = pr.request_id
WHERE rp.customer_id = $1
ORDER BY rp.joined_at DESC
`

func (q *Queries) ListRequestsByCustomer(ctx context.Context, customerID uuid.UUID) ([]PurchaseRequest, error) {
	rows, err := q.db.Query(ctx, listRequestsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurchaseRequest{}
	for rows.Next() {
		var i PurchaseRequest
		if err := rows.Scan(
			&i.RequestID,
			&i.ItemName,
			&i.Description,
			&i.Category,
			&i.Status,
			&i.TotalCustomers,
			&i.TotalQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRequest = `-- name: LockRequest :one
SELECT request_id, item_name, description, category, status, total_customers, total_quantity, created_at, updated_at FROM purchase_request
WHERE request_id = $1
FOR UPDATE
`

// Serializes concurrent joins/leaves on the same request so demand recalculation
// cannot interleave and land on a stale total.
func (q *Queries) LockRequest(ctx context.Context, requestID uuid.UUID) (PurchaseRequest, error) {
	row := q.db.QueryRow(ctx, lockRequest, requestID)
	var i PurchaseRequest
	err := row.Scan(
		&i.RequestID,
		&i.ItemName,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.TotalCustomers,
		&i.TotalQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recalculateDemand = `-- name: RecalculateDemand :one
UPDATE purchase_request pr
SET total_customers = d.total_customers,
    total_quantity  = d.total_quantity,
    updated_at      = now()
FROM (
    SELECT COUNT(*)::int                       AS total_customers,
           COALESCE(SUM(quantity), 0)::bigint  AS total_quantity
    FROM request_participant
    WHERE request_id = $1
) d
WHERE pr.request_id = $1
RETURNING pr.request_id, pr.item_name, pr.description, pr.category, pr.status, pr.total_customers, pr.total_quantity, pr.created_at, pr.updated_at
`

// R4: the service, not the caller, owns totalCustomers and totalQuantity. Recomputed
// from request_participant in the same transaction as the mutation that changed it.
func (q *Queries) RecalculateDemand(ctx context.Context, requestID uuid.UUID) (PurchaseRequest, error) {
	row := q.db.QueryRow(ctx, recalculateDemand, requestID)
	var i PurchaseRequest
	err := row.Scan(
		&i.RequestID,
		&i.ItemName,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.TotalCustomers,
		&i.TotalQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateParticipantQuantity = `-- name: UpdateParticipantQuantity :one
UPDATE request_participant
SET quantity = $1
WHERE request_id = $2 AND customer_id = $3
RETURNING participant_id, request_id, customer_id, quantity, joined_at
`

type UpdateParticipantQuantityParams struct {
	Quantity   int32
	RequestID  uuid.UUID
	CustomerID uuid.UUID
}

func (q *Queries) UpdateParticipantQuantity(ctx context.Context, arg UpdateParticipantQuantityParams) (RequestParticipant, error) {
	row := q.db.QueryRow(ctx, updateParticipantQuantity, arg.Quantity, arg.RequestID, arg.CustomerID)
	var i RequestParticipant
	err := row.Scan(
		&i.ParticipantID,
		&i.RequestID,
		&i.CustomerID,
		&i.Quantity,
		&i.JoinedAt,
	)
	return i, err
}
