// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEffectiveAccess = `-- name: CountEffectiveAccess :one
SELECT COUNT(*) FROM contact_access
WHERE seller_id = $1
  AND customer_id = $2
  AND ($3::uuid IS NULL OR request_id = $3::uuid)
  AND status = 'GRANTED'
  AND (expires_at IS NULL OR expires_at > now())
`

type CountEffectiveAccessParams struct {
	SellerID   uuid.UUID
	CustomerID uuid.UUID
	RequestID  pgtype.UUID
}

// Backs the internal permission check: may this seller reach this customer?
func (q *Queries) CountEffectiveAccess(ctx context.Context, arg CountEffectiveAccessParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEffectiveAccess, arg.SellerID, arg.CustomerID, arg.RequestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getContactAccess = `-- name: GetContactAccess :one
SELECT access_id, seller_id, customer_id, request_id, offer_id, status, granted_by, granted_at, expires_at FROM contact_access
WHERE access_id = $1
`

func (q *Queries) GetContactAccess(ctx context.Context, accessID uuid.UUID) (ContactAccess, error) {
	row := q.db.QueryRow(ctx, getContactAccess, accessID)
	var i ContactAccess
	err := row.Scan(
		&i.AccessID,
		&i.SellerID,
		&i.CustomerID,
		&i.RequestID,
		&i.OfferID,
		&i.Status,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getDecisionByOffer = `-- name: GetDecisionByOffer :one
SELECT decision_id, offer_id, admin_user_id, decision, reason, decided_at FROM offer_decision
WHERE offer_id = $1
`

func (q *Queries) GetDecisionByOffer(ctx context.Context, offerID uuid.UUID) (OfferDecision, error) {
	row := q.db.QueryRow(ctx, getDecisionByOffer, offerID)
	var i OfferDecision
	err := row.Scan(
		&i.DecisionID,
		&i.OfferID,
		&i.AdminUserID,
		&i.Decision,
		&i.Reason,
		&i.DecidedAt,
	)
	return i, err
}

const grantContactAccess = `-- name: GrantContactAccess :one
INSERT INTO contact_access (seller_id, customer_id, request_id, offer_id, granted_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING access_id, seller_id, customer_id, request_id, offer_id, status, granted_by, granted_at, expires_at
`

type GrantContactAccessParams struct {
	SellerID   uuid.UUID
	CustomerID uuid.UUID
	RequestID  uuid.UUID
	OfferID    uuid.UUID
	GrantedBy  uuid.UUID
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) GrantContactAccess(ctx context.Context, arg GrantContactAccessParams) (ContactAccess, error) {
	row := q.db.QueryRow(ctx, grantContactAccess,
		arg.SellerID,
		arg.CustomerID,
		arg.RequestID,
		arg.OfferID,
		arg.GrantedBy,
		arg.ExpiresAt,
	)
	var i ContactAccess
	err := row.Scan(
		&i.AccessID,
		&i.SellerID,
		&i.CustomerID,
		&i.RequestID,
		&i.OfferID,
		&i.Status,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listContactAccess = `-- name: ListContactAccess :many
SELECT access_id, seller_id, customer_id, request_id, offer_id, status, granted_by, granted_at, expires_at FROM contact_access
WHERE ($1::uuid IS NULL OR seller_id = $1::uuid)
  AND ($2::uuid IS NULL OR request_id = $2::uuid)
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY granted_at DESC
LIMIT $5 OFFSET $4
`

type ListContactAccessParams struct {
	SellerID     pgtype.UUID
	RequestID    pgtype.UUID
	Status       pgtype.Text
	ResultOffset int32
	ResultLimit  int32
}

func (q *Queries) ListContactAccess(ctx context.Context, arg ListContactAccessParams) ([]ContactAccess, error) {
	rows, err := q.db.Query(ctx, listContactAccess,
		arg.SellerID,
		arg.RequestID,
		arg.Status,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactAccess{}
	for rows.Next() {
		var i ContactAccess
		if err := rows.Scan(
			&i.AccessID,
			&i.SellerID,
			&i.CustomerID,
			&i.RequestID,
			&i.OfferID,
			&i.Status,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantedForSellerRequest = `-- name: ListGrantedForSellerRequest :many
SELECT access_id, seller_id, customer_id, request_id, offer_id, status, granted_by, granted_at, expires_at FROM contact_access
WHERE seller_id = $1
  AND request_id = $2
  AND status = 'GRANTED'
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY granted_at
`

type ListGrantedForSellerRequestParams struct {
	SellerID  uuid.UUID
	RequestID uuid.UUID
}

// R9: what a seller is allowed to read for one request. A grant counts only while it
// is GRANTED and unexpired, so revoking or expiring one takes effect on the next call
// rather than needing a sweep.
func (q *Queries) ListGrantedForSellerRequest(ctx context.Context, arg ListGrantedForSellerRequestParams) ([]ContactAccess, error) {
	rows, err := q.db.Query(ctx, listGrantedForSellerRequest, arg.SellerID, arg.RequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactAccess{}
	for rows.Next() {
		var i ContactAccess
		if err := rows.Scan(
			&i.AccessID,
			&i.SellerID,
			&i.CustomerID,
			&i.RequestID,
			&i.OfferID,
			&i.Status,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDecision = `-- name: RecordDecision :one
INSERT INTO offer_decision (offer_id, admin_user_id, decision, reason)
VALUES ($1, $2, $3, $4)
RETURNING decision_id, offer_id, admin_user_id, decision, reason, decided_at
`

type RecordDecisionParams struct {
	OfferID     uuid.UUID
	AdminUserID uuid.UUID
	Decision    string
	Reason      string
}

func (q *Queries) RecordDecision(ctx context.Context, arg RecordDecisionParams) (OfferDecision, error) {
	row := q.db.QueryRow(ctx, recordDecision,
		arg.OfferID,
		arg.AdminUserID,
		arg.Decision,
		arg.Reason,
	)
	var i OfferDecision
	err := row.Scan(
		&i.DecisionID,
		&i.OfferID,
		&i.AdminUserID,
		&i.Decision,
		&i.Reason,
		&i.DecidedAt,
	)
	return i, err
}

const revokeContactAccess = `-- name: RevokeContactAccess :one
UPDATE contact_access
SET status = 'REVOKED'
WHERE access_id = $1 AND status = 'GRANTED'
RETURNING access_id, seller_id, customer_id, request_id, offer_id, status, granted_by, granted_at, expires_at
`

// Revoking is a status change, not a delete: the grant is part of the audit history of
// who was allowed to reach whom, and deleting the row would erase that.
func (q *Queries) RevokeContactAccess(ctx context.Context, accessID uuid.UUID) (ContactAccess, error) {
	row := q.db.QueryRow(ctx, revokeContactAccess, accessID)
	var i ContactAccess
	err := row.Scan(
		&i.AccessID,
		&i.SellerID,
		&i.CustomerID,
		&i.RequestID,
		&i.OfferID,
		&i.Status,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.ExpiresAt,
	)
	return i, err
}
