// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ContactAccess struct {
	AccessID   uuid.UUID
	SellerID   uuid.UUID
	CustomerID uuid.UUID
	RequestID  uuid.UUID
	OfferID    uuid.UUID
	Status     string
	GrantedBy  uuid.UUID
	GrantedAt  time.Time
	ExpiresAt  pgtype.Timestamptz
}

type OfferDecision struct {
	DecisionID  uuid.UUID
	OfferID     uuid.UUID
	AdminUserID uuid.UUID
	Decision    string
	Reason      string
	DecidedAt   time.Time
}
