// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Backs the internal permission check: may this seller reach this customer?
	CountEffectiveAccess(ctx context.Context, arg CountEffectiveAccessParams) (int64, error)
	GetContactAccess(ctx context.Context, accessID uuid.UUID) (ContactAccess, error)
	GetDecisionByOffer(ctx context.Context, offerID uuid.UUID) (OfferDecision, error)
	GrantContactAccess(ctx context.Context, arg GrantContactAccessParams) (ContactAccess, error)
	ListContactAccess(ctx context.Context, arg ListContactAccessParams) ([]ContactAccess, error)
	// R9: what a seller is allowed to read for one request. A grant counts only while it
	// is GRANTED and unexpired, so revoking or expiring one takes effect on the next call
	// rather than needing a sweep.
	ListGrantedForSellerRequest(ctx context.Context, arg ListGrantedForSellerRequestParams) ([]ContactAccess, error)
	RecordDecision(ctx context.Context, arg RecordDecisionParams) (OfferDecision, error)
	// Revoking is a status change, not a delete: the grant is part of the audit history of
	// who was allowed to reach whom, and deleting the row would erase that.
	RevokeContactAccess(ctx context.Context, accessID uuid.UUID) (ContactAccess, error)
}

var _ Querier = (*Queries)(nil)
