/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/contact-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List contact-access grants
         * @description The audit trail behind the phone-number rule: who was granted access to
         *     which request, and whether it is still live.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by request */
                    requestId?: string;
                    /** @description Filter by seller */
                    sellerId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["admin.contactAccessResponse"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Not an ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/contact-access/{accessId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a contact-access grant
         * @description The grant is marked revoked rather than deleted, so the audit trail
         *     still shows it was once given.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Grant id */
                    accessId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["admin.contactAccessResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Not an ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description No such grant */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/offers/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List offers awaiting a decision
         * @description The admin queue. Offers stay here until approved or rejected.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["admin.pendingOfferResponse"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Not an ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/offers/{offerId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve an offer and grant contact access
         * @description Approving is what unlocks the seller's access to the customers' phone
         *     numbers on that request - the single gate in the whole flow. Returns
         *     201: the decision is a new record, not a mutation of the offer.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Offer id */
                    offerId: string;
                };
                cookie?: never;
            };
            /** @description Reason recorded with the decision */
            requestBody?: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["admin.decisionBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["admin.decisionResponse"];
                    };
                };
                /** @description Malformed id or body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Not an ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description No such offer */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Already decided */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/offers/{offerId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject an offer
         * @description Grants nothing: a rejected offer leaves the seller without contact access.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Offer id */
                    offerId: string;
                };
                cookie?: never;
            };
            /** @description Reason recorded with the decision */
            requestBody?: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["admin.decisionBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["admin.decisionResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Not an ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Already decided */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contacts/requests/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the customer contacts for a request
         * @description The only public endpoint in the platform that returns a phone number,
         *     and only to a seller whose offer was approved for this request. The
         *     sellerId is resolved from the token, never read from the request.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Request id */
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["admin.contactsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Not a SELLER, or no access granted for this request */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "admin.contact": {
            customerId?: string;
            firstName?: string;
            lastName?: string;
            phoneNumber?: string;
        };
        "admin.contactAccessResponse": {
            accessId?: string;
            customerId?: string;
            expiresAt?: string;
            grantedAt?: string;
            grantedBy?: string;
            offerId?: string;
            requestId?: string;
            sellerId?: string;
            status?: string;
        };
        "admin.contactsResponse": {
            contacts?: components["schemas"]["admin.contact"][];
            requestId?: string;
        };
        "admin.decisionBody": {
            reason?: string;
        };
        "admin.decisionResponse": {
            adminUserId?: string;
            /**
             * @description How many customers the approval exposed to the seller. Zero for a rejection,
             *     which grants nothing (R8).
             */
            contactsGranted?: number;
            decidedAt?: string;
            decision?: string;
            decisionId?: string;
            offerId?: string;
            reason?: string;
        };
        "admin.pendingOfferResponse": {
            availableQuantity?: number;
            currency?: string;
            description?: string;
            offerId?: string;
            pricePerUnit?: string;
            requestId?: string;
            sellerId?: string;
            status?: string;
        };
        "httpx.ErrorBody": {
            message?: string;
            status?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
