/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Offer
         * @description R5: only against an existing request. R6: always starts PENDING.
         */
        post: operations["submit_offer_api_offers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Offers */
        get: operations["my_offers_api_offers_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/request/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Offers For Request
         * @description Offers against one request.
         *
         *     Customers and admins see them in full. A seller sees their own offer in full but
         *     only the anonymised view of a competitor's, so browsing the market cannot tell them
         *     who they are bidding against.
         */
        get: operations["offers_for_request_api_offers_request__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/{offer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Offer */
        get: operations["get_offer_api_offers__offer_id__get"];
        /** Update Offer */
        put: operations["update_offer_api_offers__offer_id__put"];
        post?: never;
        /** Cancel Offer */
        delete: operations["cancel_offer_api_offers__offer_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CompetingOfferOut
         * @description What one seller is allowed to learn about another seller's offer on the same
         *     request: that it exists and what it costs, never who made it.
         *
         *     Sellers still need to see the competitive field to price sensibly, but sellerId is
         *     withheld so a marketplace participant cannot build a picture of who they are
         *     bidding against. Customers and admins get the full OfferOut instead.
         */
        CompetingOfferOut: {
            /**
             * Offerid
             * Format: uuid
             */
            offerId: string;
            /**
             * Requestid
             * Format: uuid
             */
            requestId: string;
            /** Availablequantity */
            availableQuantity: number;
            /** Priceperunit */
            pricePerUnit: string;
            /** Currency */
            currency: string;
            /** Status */
            status: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OfferCreate */
        OfferCreate: {
            /**
             * Requestid
             * Format: uuid
             */
            requestId: string;
            /** Availablequantity */
            availableQuantity: number;
            /** Priceperunit */
            pricePerUnit: number | string;
            /** Currency */
            currency: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** OfferOut */
        OfferOut: {
            /**
             * Offerid
             * Format: uuid
             */
            offerId: string;
            /**
             * Requestid
             * Format: uuid
             */
            requestId: string;
            /**
             * Sellerid
             * Format: uuid
             */
            sellerId: string;
            /** Availablequantity */
            availableQuantity: number;
            /** Priceperunit */
            pricePerUnit: string;
            /** Currency */
            currency: string;
            /** Description */
            description: string;
            /** Status */
            status: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** OfferUpdate */
        OfferUpdate: {
            /** Availablequantity */
            availableQuantity: number;
            /** Priceperunit */
            pricePerUnit: number | string;
            /** Currency */
            currency: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submit_offer_api_offers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_offers_api_offers_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    offers_for_request_api_offers_request__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["OfferOut"] | components["schemas"]["CompetingOfferOut"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_offer_api_offers__offer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferOut"] | components["schemas"]["CompetingOfferOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_offer_api_offers__offer_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_offer_api_offers__offer_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
