/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse open demand
         * @description Open to everyone, signed in or not. It carries aggregate totals and no
         *     participant identity, so there is nothing here a token would protect.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Match on item name */
                    q?: string;
                    /** @description Filter by category */
                    category?: string;
                    /** @description OPEN or INACTIVE */
                    status?: string;
                    /** @description Page size, 1-100 */
                    limit?: number;
                    /** @description Rows to skip */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["requests.requestResponse"][];
                    };
                };
                /** @description Bad paging parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a purchase request
         * @description Opens a request other customers can join. The caller becomes its first
         *     participant; the customerId is resolved from the token, never sent.
         *     If an open request already carries this item name, nothing is created:
         *     the 409 comes back with that request attached, and joining it is the
         *     customer's own call through the participants endpoint. A merely similar
         *     name is not refused - see /api/requests/similar, which is what the
         *     new-request form shows while the name is being typed.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Item, category and the caller's own quantity */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["requests.createRequestBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["requests.requestResponse"];
                    };
                };
                /** @description Validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Not a CUSTOMER, or no customer profile */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Already a participant, or this item is already open demand */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["requests.requestExistsBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's own requests */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["requests.requestResponse"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Not a CUSTOMER */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find open requests whose item name is close to this one
         * @description Powers the suggestions a customer sees while naming an item, and is the
         *     same match a create is refused on. Open to everyone, signed in or not:
         *     it returns the browse projection, ranked by similarity.
         */
        get: {
            parameters: {
                query: {
                    /** @description The item name being typed */
                    itemName: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["requests.requestResponse"][];
                    };
                };
                /** @description itemName is required */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one request with its aggregated demand
         * @description Open to everyone, signed in or not. Returns totals, not the participant
         *     list: who joined is withheld from the public projection and served only
         *     on the internal endpoint.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Request id */
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["requests.requestResponse"];
                    };
                };
                /** @description Malformed id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{requestId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join a request with a quantity
         * @description Adds the caller's demand to the aggregate. Joining twice is refused;
         *     use the participants/me endpoint to change a quantity.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Request id */
                    requestId: string;
                };
                cookie?: never;
            };
            /** @description Quantity wanted */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["requests.quantityBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["requests.requestResponse"];
                    };
                };
                /** @description Quantity must be positive */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Not a CUSTOMER */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Already joined, or the request is not OPEN */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{requestId}/participants/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change how much the caller wants
         * @description Addressed as participants/me rather than by participant id: a customer
         *     can only ever change their own row, so there is nothing else to name.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Request id */
                    requestId: string;
                };
                cookie?: never;
            };
            /** @description New quantity */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["requests.quantityBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["requests.requestResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Not a CUSTOMER */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Not a participant */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description The request is no longer OPEN */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
            };
        };
        post?: never;
        /** Withdraw from a request */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Request id */
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Withdrawn */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Not a CUSTOMER */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description Not a participant */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
                /** @description The request is no longer OPEN */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorBody"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "httpx.ErrorBody": {
            message?: string;
            status?: number;
        };
        "requests.createRequestBody": {
            category?: string;
            description?: string;
            itemName?: string;
            quantity?: number;
        };
        "requests.quantityBody": {
            quantity?: number;
        };
        "requests.requestExistsBody": {
            existing?: components["schemas"]["requests.requestResponse"];
            message?: string;
            status?: number;
        };
        "requests.requestResponse": {
            category?: string;
            createdAt?: string;
            createdBy?: string;
            description?: string;
            /**
             * @description Set when this request carries the searched-for name outright rather than merely
             *     something like it. It is what tells a client that creating is not on offer here -
             *     only joining is - so the form can say so before the customer finds out from a 409.
             */
            exact?: boolean;
            itemName?: string;
            requestId?: string;
            /**
             * @description How close this request's item name is to the one that was searched for, 0 to 1.
             *     Carried only by the near-match endpoints, so the caller can order and explain the
             *     suggestions rather than being handed an unranked list.
             */
            similarity?: number;
            status?: string;
            totalCustomers?: number;
            totalQuantity?: number;
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
